version: 0.2

env:
  parameter-store:
    AWS_ACCESS_KEY_ID_PARAM: /CodeBuild/blog/AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY_PARAM: /CodeBuild/blog/AWS_SECRET_ACCESS_KEY
     
phases:
  install:
    commands: 
      - npm install -g hexo-cli
      - npm install
      - apt-get update
      - apt-get install -y awscli

  build: 
    commands:
      - hexo generate

  post_build: 
    commands:
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PARAM
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PARAM
      - cd public/ && aws s3 sync . s3://campbellpeter.com/
